import 'package:flutter/material.dart';
import 'package:test55/Models/Building.dart';
import 'package:test55/descendents/collectionView.dart';
class HomeScreen extends StatelessWidget {
  List<Building> get buildings {
    return [Building(title: "Sarala Flats", address: "234, Kurla roal, near khao gali", date: "31 Dec 2019", descript: "Fully Furnished flat full facility available", image: "Images/hdBuilding.jpg", bhk: "2 & 3 BHK", startingPrise: "15Lakh Onwards", companiImage: "Images/homeb.jpeg"),
            Building(title: "Ramola Flats", address: "234, Kurla roal, near khao gali", date: "31 Dec 2019", descript: "Fully Furnished flat full facility available", image: "Images/hdBuilding.jpg", bhk: "2 & 3 BHK", startingPrise: "15Lakh Onwards", companiImage: "Images/homeb2.jpeg"),
            Building(title: "Sandarbh Flats", address: "234, Kurla roal, near khao gali", date: "31 Dec 2019", descript: "Fully Furnished flat full facility available", image: "Images/hdBuilding.jpg", bhk: "1 & 2 BHK", startingPrise: "15Lakh Onwards", companiImage: "Images/homeb3.png"),
            Building(title: "Shiv Sharp Flats", address: "234, Kurla roal, near khao gali", date: "31 Dec 2019", descript: "Fully Furnished flat full facility available", image: "Images/hdBuilding.jpg", bhk: "4 & 3 BHK", startingPrise: "65Lakh Onwards", companiImage: "Images/homeb4.jpeg"),
            Building(title: "Dillagi Flats", address: "234, Kurla roal, near khao gali", date: "31 Dec 2019", descript: "Fully Furnished flat full facility available", image: "Images/hdBuilding.jpg", bhk: "4 & 3 BHK", startingPrise: "60Lakh Onwards", companiImage: "Images/homeb.jpeg"),
            Building(title: "Supari Flats", address: "234, Kurla roal, near khao gali", date: "31 Dec 2019", descript: "Fully Furnished flat full facility available", image: "Images/hdBuilding.jpg", bhk: "1 & 3 BHK", startingPrise: "15Lakh Onwards", companiImage: "Images/homeb.jpeg"),
            Building(title: "Govard Flats", address: "234, Kurla roal, near khao gali", date: "31 Dec 2019", descript: "Fully Furnished flat full facility available", image: "Images/hdBuilding.jpg", bhk: "1 & 2 BHK", startingPrise: "15Lakh Onwards", companiImage: "Images/homeb4.jpeg"),
            Building(title: "Super 11 Flats", address: "234, Kurla roal, near khao gali", date: "31 Dec 2019", descript: "Fully Furnished flat full facility available", image: "Images/hdBuilding.jpg", bhk: "3 & 5 BHK", startingPrise: "95Lakh Onwards", companiImage: "Images/homeb3.png"),
            Building(title: "NewBorn Flats", address: "234, Kurla roal, near khao gali", date: "31 Dec 2019", descript: "Fully Furnished flat full facility available", image: "Images/hdBuilding.jpg", bhk: "3 & 6 BHK", startingPrise: "1Cror Onwards", companiImage: "Images/homeb2.jpeg"),
            Building(title: "Ganshyaam Flats", address: "234, Kurla roal, near khao gali", date: "31 Dec 2019", descript: "Fully Furnished flat full facility available Fully Furnished flat full facility available Fully Furnished flat full facility available Fully Furnished flat full facility available Fully Furnished flat full facility available Fully Furnished flat full facility available Fully Furnished flat full facility available Fully Furnished flat full facility available Fully Furnished flat full facility available Fully Furnished flat full facility available Fully Furnished flat full facility available Fully Furnished flat full facility available Fully Furnished flat full facility available Fully Furnished flat full facility available Fully Furnished flat full facility available Fully Furnished flat full facility available Fully Furnished flat full facility available Fully Furnished flat full facility available Fully Furnished flat full facility available Fully Furnished flat full Fully Furnished flat full facility available Fully Furnished flat full facility available Fully Furnished flat full facility available Fully Furnished flat full facility available Fully Furnished flat full facility available Fully Furnished flat full facility available Fully Furnished flat full facility available Fully Furnished flat full facility available Fully Furnished flat full facility available Fully Furnished flat full Fully Furnished flat full facility available Fully Furnished flat full facility available Fully Furnished flat full facility available Fully Furnished flat full facility available Fully Furnished flat full facility available Fully Furnished flat full facility available Fully Furnished flat full facility available Fully Furnished flat full facility available Fully Furnished flat full facility available Fully Furnished flat full Fully Furnished flat full facility available Fully Furnished flat full facility available Fully Furnished flat full facility available Fully Furnished flat full facility available Fully Furnished flat full facility available Fully Furnished flat full facility available Fully Furnished flat full facility available Fully Furnished flat full facility available Fully Furnished flat full facility available Fully Furnished flat full Fully Furnished flat full facility available Fully Furnished flat full facility available Fully Furnished flat full facility available Fully Furnished flat full facility available Fully Furnished flat full facility available Fully Furnished flat full facility available Fully Furnished flat full facility available Fully Furnished flat full facility available Fully Furnished flat full facility available Fully Furnished flat full", image: "Images/hdBuilding.jpg", bhk: "3 & 2 BHK", startingPrise: "25lakh Onwards", companiImage: "Images/homeb.jpeg"),
    ];
  }
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.white,
      appBar: AppBar(title: Text("Properties"), backgroundColor: Colors.lightBlue,),
      body: Container(child: CollectionView(buildings: buildings,), height: double.infinity,),
    );
  }
}